// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MatcherService handles file matching operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DirExists checks if a directory exists
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function DirExists(path) {
    return $Call.ByID(1916444002, path);
}

/**
 * FindMatches finds matches between torrent files and disk files
 * @param {$models.MatchRequest} req
 * @returns {$CancellablePromise<$models.MatchResponse>}
 */
export function FindMatches(req) {
    return $Call.ByID(476527029, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GenRenames generates rename operations based on matches
 * @param {$models.RenameRequest} req
 * @returns {$CancellablePromise<$models.RenameOp[]>}
 */
export function GenRenames(req) {
    return $Call.ByID(2833719546, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ScanDir scans a directory and returns all files
 * @param {string} path
 * @returns {$CancellablePromise<$models.DiskFileInfo[]>}
 */
export function ScanDir(path) {
    return $Call.ByID(3958135217, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MatchResponse.createFrom;
const $$createType1 = $models.RenameOp.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DiskFileInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
