// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QBitService handles qBittorrent operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect connects to qBittorrent
 * @param {$models.ConnectionConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function Connect(config) {
    return $Call.ByID(2643120139, config);
}

/**
 * Disconnect disconnects from qBittorrent
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(2108215021);
}

/**
 * GetTorrentFiles returns files for a specific torrent
 * @param {string} hash
 * @returns {$CancellablePromise<$models.TorrentFile[]>}
 */
export function GetTorrentFiles(hash) {
    return $Call.ByID(1264571836, hash).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetTorrents returns all torrents
 * @returns {$CancellablePromise<$models.TorrentInfo[]>}
 */
export function GetTorrents() {
    return $Call.ByID(3031147382).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetVersion returns the qBittorrent version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1877302715);
}

/**
 * IsConnected returns whether we're connected to qBittorrent
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected() {
    return $Call.ByID(3015515214);
}

/**
 * RecheckTorrent triggers a hash recheck for the torrent
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function RecheckTorrent(hash) {
    return $Call.ByID(3112118224, hash);
}

/**
 * RenameFile renames a file in qBittorrent
 * @param {string} hash
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(hash, oldPath, newPath) {
    return $Call.ByID(471807579, hash, oldPath, newPath);
}

/**
 * SetFilePriority sets the priority for files in a torrent
 * IDs is a comma-separated list of file indices (e.g., "0,1,2")
 * Priority: 0 = do not download, 1 = normal, 6 = high, 7 = maximum
 * @param {string} hash
 * @param {string} fileIDs
 * @param {number} priority
 * @returns {$CancellablePromise<void>}
 */
export function SetFilePriority(hash, fileIDs, priority) {
    return $Call.ByID(1984806499, hash, fileIDs, priority);
}

/**
 * SetTorrentLocation sets the download location for a torrent
 * @param {string} hash
 * @param {string} location
 * @returns {$CancellablePromise<void>}
 */
export function SetTorrentLocation(hash, location) {
    return $Call.ByID(1731436990, hash, location);
}

// Private type creation functions
const $$createType0 = $models.TorrentFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.TorrentInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
