// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MatcherService handles file matching operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DirectoryExists checks if a directory exists
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function DirectoryExists(path) {
    return $Call.ByID(969128502, path);
}

/**
 * FindMatches finds matches between torrent files and disk files
 * @param {$models.MatchRequest} req
 * @returns {$CancellablePromise<$models.MatchResponse>}
 */
export function FindMatches(req) {
    return $Call.ByID(2305065193, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GenerateRenames generates rename operations based on matches
 * @param {$models.RenameRequest} req
 * @returns {$CancellablePromise<$models.RenameOperation[]>}
 */
export function GenerateRenames(req) {
    return $Call.ByID(3464538835, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ScanDirectory scans a directory and returns all files
 * @param {string} path
 * @returns {$CancellablePromise<$models.DiskFileInfo[]>}
 */
export function ScanDirectory(path) {
    return $Call.ByID(2011767925, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MatchResponse.createFrom;
const $$createType1 = $models.RenameOperation.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DiskFileInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
