// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QBitService handles qBittorrent operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect connects to qBittorrent
 * @param {$models.ConnectionConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function Connect(config) {
    return $Call.ByID(2541156495, config);
}

/**
 * Disconnect disconnects from qBittorrent
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(1241630081);
}

/**
 * GetTorrentFiles returns files for a specific torrent
 * @param {string} hash
 * @returns {$CancellablePromise<$models.TorrentFileInfo[]>}
 */
export function GetTorrentFiles(hash) {
    return $Call.ByID(2664721056, hash).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetTorrents returns all torrents
 * @returns {$CancellablePromise<$models.TorrentInfo[]>}
 */
export function GetTorrents() {
    return $Call.ByID(537742322).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetVersion returns the qBittorrent version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(507000807);
}

/**
 * IsConnected returns whether we're connected to qBittorrent
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected() {
    return $Call.ByID(2935823650);
}

/**
 * RenameFile renames a file in qBittorrent
 * @param {string} hash
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(hash, oldPath, newPath) {
    return $Call.ByID(3420300407, hash, oldPath, newPath);
}

/**
 * SetTorrentLocation sets the download location for a torrent
 * @param {string} hash
 * @param {string} location
 * @returns {$CancellablePromise<void>}
 */
export function SetTorrentLocation(hash, location) {
    return $Call.ByID(303992562, hash, location);
}

// Private type creation functions
const $$createType0 = $models.TorrentFileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.TorrentInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
