// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiskFile represents a file on the disk
 */
export class DiskFile {
    /**
     * Creates a new DiskFile instance.
     * @param {Partial<DiskFile>} [$$source = {}] - The source object to create the DiskFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskFile(/** @type {Partial<DiskFile>} */($$parsedSource));
    }
}

/**
 * TorrentFileInfo represents a file from a torrent that needs matching
 */
export class TorrentFileInfo {
    /**
     * Creates a new TorrentFileInfo instance.
     * @param {Partial<TorrentFileInfo>} [$$source = {}] - The source object to create the TorrentFileInfo.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TorrentFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TorrentFileInfo(/** @type {Partial<TorrentFileInfo>} */($$parsedSource));
    }
}
